runner:
  golint:
    cmd: golint ./...
    errorformat:
      - "%f:%l:%c: %m"
    level: warning
  govet:
    cmd: go vet -vettool=`which complecfunc` ./testdata/src/a/
    errorformat:
      - "%f:%l:%c: %m"